spring:
  application:
    name: api-gateway

server:
  port: ${SERVER_PORT:8091}


country:
  service:
    url: ${COUNTRY_SERVICE_URL:http://localhost:8080}


consumer:
  service:
    url: ${CONSUMER_SERVICE_URL:http://localhost:8081}
