server:
  port: ${port:8080}

spring:
  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/${POSTGRES_DB}}
    username: ${datasource.username:${POSTGRES_USER}}
    password: ${datasource.password:${POSTGRES_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    mongodb:
      host: ${mongo.host:${MONGO_HOST}}
      port: ${mongo.port:${MONGO_PORT}}
      database: ${mongo.database:${MONGO_DB}}

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.apicountries.model

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.example.apicountries.model


country:
  url: ${COUNTRY_URL}

topic:
  name: sandbox